seed = 0
function = "bin.base.main"
n_trials = 100
sampler_type = "BruteForceSampler"

[space]
seed = 0
n_steps = 1000
patience = 100

[space.data]
cache = false
path = "data/facebook"
setting = "transductive"
add_self_loops = false
num_policy = [
    "_tune_",
    "categorical",
    [
        "standard",
        "none",
    ],
]
external_split = true

[space.data.graph_encodings]
preprocess = "noisy-quantile-normal"

[space.data.graph_encodings.lap_pe]
k = 14

[space.data.graph_encodings.degree]
log = true

[space.data.graph_encodings.pagerank]
log = true

[space.data.nfa]
num_modes = [
    "mean",
]

[space.data.pca.params]
dim = 1000000

[space.model.backbone]
type = "BaseGraphBackbone"
conv_name = "sage"
norm_name = "layer"
residual = true
n_layers = 3
d_hidden = 512
dropout = [
    "_tune_",
    "categorical",
    [
        0.0,
        0.1,
        0.2,
    ],
]
activation = "gelu"

[space.model.pearl]
batch_size = 8
output_dim = 16

[space.model.pearl.backbone]
type = "BaseGraphBackbone"
conv_name = "gcn"
norm_name = "none"
residual = false
n_layers = 3
d_hidden = 512
dropout = 0.1
activation = "gelu"

[space.optimizer]
type = "AdamW"
lr = [
    "_tune_",
    "categorical",
    [
        3e-05,
        0.0001,
        0.0003,
        0.001,
        0.003,
    ],
]
weight_decay = 0.0
