function = "bin.g2t_fm.main"
n_seeds = 10

[base_config]
patience = 16
amp = true
n_epochs = -1
batch_size = 1
epoch_size = 10
min_train_ratio = 0.75
seq_len_pred = 1024
finetune_mode = "full"

[base_config.tabpfn]
untie_pos_embeddings = false
untie_value_embeddings = false
shuffle_labels = true

[base_config.tabpfn.tabpfn_config]
nhead = 6
emsize = 192
nlayers = 12
nhid_factor = 4

[base_config.tabpfn.num_embeddings]
type = "LinearEmbeddings"

[base_config.optimizer]
type = "AdamW"
lr = 3.871318040182814e-05
weight_decay = 0.0

[base_config.data]
cache = false
path = "data/facebook"
setting = "transductive"
num_policy = "standard"
external_split = true

[base_config.data.nfa]
num_modes = [
    "mean",
]
