seed = 0
function = "bin.g2t_fm.main"
n_trials = 100
sampler_type = "BruteForceSampler"

[space]
seed = 0
patience = 16
amp = true
n_epochs = 0
batch_size = 1
epoch_size = 10
min_train_ratio = 0.75
seq_len_pred = 1024
finetune_mode = "full"

[space.tabpfn]
untie_pos_embeddings = false
untie_value_embeddings = false
shuffle_labels = true

[space.tabpfn.tabpfn_config]
nhead = 6
emsize = 192
nlayers = 12
nhid_factor = 4

[space.tabpfn.num_embeddings]
type = "LinearEmbeddings"

[space.optimizer]
type = "AdamW"
lr = 0.0003
weight_decay = 0.0

[space.data]
cache = false
path = "data/hm-prices"
setting = "transductive"
num_policy = "noisy-quantile-normal"
cat_policy = "ordinal"
internal_split_name = "RL"

[space.data.nfa]
