function = "bin.lightgbm_.main"
n_seeds = 10

[base_config.data]
cache = false
path = "data/hm-prices"
setting = "transductive"
add_self_loops = false
num_policy = "none"
ratio_policy = "none"
cat_policy = "ordinal"
internal_split_name = "RL"

[base_config.data.graph_encodings]
preprocess = "noisy-quantile-normal"

[base_config.data.graph_encodings.lap_pe]
k = 14

[base_config.data.graph_encodings.degree]
log = true

[base_config.data.graph_encodings.pagerank]
log = true

[base_config.data.nfa]

[base_config.model]
n_estimators = 4000
n_jobs = 4
verbose = -1
feature_fraction = 0.7073309699952618
lambda_l2 = 0.8171478915115865
learning_rate = 0.05073432032394333
num_leaves = 18
min_sum_hessian_in_leaf = 0.5079406641139773
bagging_fraction = 0.8060478613612108
stopping_rounds = 1000
device_type = "cpu"

[base_config.fit]

[base_config.pearl]
batch_size = 8
output_dim = 16

[base_config.pearl.backbone]
type = "BaseGraphBackbone"
conv_name = "gcn"
norm_name = "none"
residual = false
n_layers = 3
d_hidden = 512
dropout = 0.1
activation = "gelu"
