function = "bin.lightgbm_.main"
n_seeds = 10

[base_config.data]
cache = false
path = "data/twitch-views"
setting = "transductive"
add_self_loops = false
num_policy = "none"
ratio_policy = "none"
cat_policy = "ordinal"
internal_split_name = "RL"

[base_config.data.graph_encodings]
preprocess = "noisy-quantile-normal"

[base_config.data.graph_encodings.lap_pe]
k = 14

[base_config.data.graph_encodings.degree]
log = true

[base_config.data.graph_encodings.pagerank]
log = true

[base_config.data.nfa]

[base_config.model]
n_estimators = 4000
n_jobs = 4
verbose = -1
feature_fraction = 0.7086907598688748
lambda_l2 = 8.460735649953767
learning_rate = 0.003986238235358895
num_leaves = 67
min_sum_hessian_in_leaf = 14.180770487603418
bagging_fraction = 0.5630763553595042
stopping_rounds = 1000
device_type = "cpu"

[base_config.fit]

[base_config.pearl]
batch_size = 8
output_dim = 16

[base_config.pearl.backbone]
type = "BaseGraphBackbone"
conv_name = "gcn"
norm_name = "none"
residual = false
n_layers = 3
d_hidden = 512
dropout = 0.1
activation = "gelu"
